# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_r testthat

language: R
sudo: false
cache: packages
